python projectProgressChecker.py -f ../docs/assets/data/11765.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/11766.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/11767.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/11768.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/11769.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/11770.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/13827.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14377.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14525.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14526.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14527.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14528.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14529.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14903.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16400.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16402.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16416.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16418.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16421.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16449.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16451.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16810.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16920.json -st alternate
cmd