python projectProgressChecker.py -f ../docs/assets/data/13807.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/13808.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14184.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14290.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14291.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14292.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14293.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14294.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14295.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14296.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14297.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14298.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14299.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14500.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14501.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14502.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14503.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14504.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14505.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14506.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14507.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14508.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14509.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14510.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14511.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14520.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14521.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14523.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14524.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14525.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14526.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14527.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14528.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14529.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14530.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14630.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14631.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14821.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14822.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14825.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14827.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14828.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14836.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14852.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14903.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16400.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16401.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16402.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16403.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16416.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16418.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16421.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16422.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16423.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16431.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16448.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16449.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16450.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16452.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16453.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16454.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16455.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16456.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16500.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16600.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16800.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16801.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16802.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16803.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16804.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16805.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16806.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16810.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16920.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/17200.json -st alternate
cmd