python projectProgressChecker.py -f ../docs/assets/data/13827.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/13828.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/13829.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/13830.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14377.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14520.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14521.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14525.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14821.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14822.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14825.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14827.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14828.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14852.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14903.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16449.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16451.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16801.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16804.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16810.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16920.json -st alternate
cmd
