python projectProgressChecker.py -f ../docs/assets/data/11765.json
python projectProgressChecker.py -f ../docs/assets/data/11766.json
python projectProgressChecker.py -f ../docs/assets/data/11767.json
python projectProgressChecker.py -f ../docs/assets/data/11768.json
python projectProgressChecker.py -f ../docs/assets/data/11769.json
python projectProgressChecker.py -f ../docs/assets/data/11770.json
python projectProgressChecker.py -f ../docs/assets/data/13807.json
python projectProgressChecker.py -f ../docs/assets/data/13808.json
python projectProgressChecker.py -f ../docs/assets/data/14184.json
python projectProgressChecker.py -f ../docs/assets/data/14290.json
python projectProgressChecker.py -f ../docs/assets/data/14291.json
python projectProgressChecker.py -f ../docs/assets/data/14292.json
python projectProgressChecker.py -f ../docs/assets/data/14293.json
python projectProgressChecker.py -f ../docs/assets/data/14294.json
python projectProgressChecker.py -f ../docs/assets/data/14295.json
python projectProgressChecker.py -f ../docs/assets/data/14296.json
python projectProgressChecker.py -f ../docs/assets/data/14297.json
python projectProgressChecker.py -f ../docs/assets/data/14298.json
python projectProgressChecker.py -f ../docs/assets/data/14299.json
python projectProgressChecker.py -f ../docs/assets/data/14500.json
python projectProgressChecker.py -f ../docs/assets/data/14501.json
python projectProgressChecker.py -f ../docs/assets/data/14502.json
python projectProgressChecker.py -f ../docs/assets/data/14503.json
python projectProgressChecker.py -f ../docs/assets/data/14504.json
python projectProgressChecker.py -f ../docs/assets/data/14505.json
python projectProgressChecker.py -f ../docs/assets/data/14506.json
python projectProgressChecker.py -f ../docs/assets/data/14507.json
python projectProgressChecker.py -f ../docs/assets/data/14508.json
python projectProgressChecker.py -f ../docs/assets/data/14509.json
python projectProgressChecker.py -f ../docs/assets/data/14510.json
python projectProgressChecker.py -f ../docs/assets/data/14511.json
python projectProgressChecker.py -f ../docs/assets/data/14520.json
python projectProgressChecker.py -f ../docs/assets/data/14521.json
python projectProgressChecker.py -f ../docs/assets/data/14523.json
python projectProgressChecker.py -f ../docs/assets/data/14524.json
python projectProgressChecker.py -f ../docs/assets/data/14525.json
python projectProgressChecker.py -f ../docs/assets/data/14526.json
python projectProgressChecker.py -f ../docs/assets/data/14527.json
python projectProgressChecker.py -f ../docs/assets/data/14528.json
python projectProgressChecker.py -f ../docs/assets/data/14529.json
python projectProgressChecker.py -f ../docs/assets/data/14530.json
python projectProgressChecker.py -f ../docs/assets/data/14630.json
python projectProgressChecker.py -f ../docs/assets/data/14631.json
python projectProgressChecker.py -f ../docs/assets/data/14836.json
python projectProgressChecker.py -f ../docs/assets/data/16400.json
python projectProgressChecker.py -f ../docs/assets/data/16402.json
python projectProgressChecker.py -f ../docs/assets/data/16416.json
python projectProgressChecker.py -f ../docs/assets/data/16418.json
python projectProgressChecker.py -f ../docs/assets/data/16421.json
python projectProgressChecker.py -f ../docs/assets/data/16449.json
python projectProgressChecker.py -f ../docs/assets/data/16600.json
python projectProgressChecker.py -f ../docs/assets/data/16800.json
python projectProgressChecker.py -f ../docs/assets/data/16801.json
python projectProgressChecker.py -f ../docs/assets/data/16804.json
python projectProgressChecker.py -f ../docs/assets/data/16810.json
python projectProgressChecker.py -f ../docs/assets/data/16920.json
cmd