python projectProgressChecker.py -f ../docs/assets/data/13807.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/13808.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14184.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14290.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14291.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14292.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14293.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14294.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14295.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14296.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14297.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14298.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14299.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14500.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14501.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14502.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14503.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14504.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14505.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14506.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14507.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14508.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14509.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14510.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14511.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14520.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14521.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14523.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14524.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14530.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14630.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14631.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14821.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14822.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/14836.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16448.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16600.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16800.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16801.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16802.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/16804.json -st alternate
python projectProgressChecker.py -f ../docs/assets/data/17200.json -st alternate
cmd