title : Folding@home

author :
  name : Anand Bhat
  github : anand-bhat
  twitter : _anandbhat

production_url : https://anand-bhat.github.io/hwtest/

JB :
  version : 0.3.0
  BASE_PATH : https://anand-bhat.github.io/hwtest/
  ASSET_PATH : https://anand-bhat.github.io/hwtest/assets
